export const AUTH = {
  GET_ERRORS: 'GET_ERRORS',
  USER_LOADING: 'USER_LOADING',
  SET_CURRENT_USER: 'SET_CURRENT_USER'
};

export const MOVIES = {
  SUCCESS: 'MOVIES_LOAD_SUCCESS',
  LOADING: 'MOVIES_LOAD',
  LOAD_FAILED: 'MOVIES_LOAD_FAILED',
  ADD_SUCCESS: 'MOVIE_ADD_SUCCESS',
  ADD_FAILED: 'MOVIE_ADD_FAILED',
  UPDATE_SUCCESS: 'MOVIE_UPDATE_SUCCESS',
  UPDATE_FAILED: 'MOVIE_UPDATE_FAILED',
  DELETE_SUCCESS: 'MOVIE_DELETE_SUCCESS',
  DELETE_FAILED: 'MOVIE_DELETE_FAILED'
};
